import deployedContracts from "./contracts/deployedContracts";

export type Location = {
  id: number;
  position: { lat: number; lng: number };
  title: string;
  address: string;
  image: string;
  region: string;
  date: string;
  venue: string;
  lumaLink?: string; // Optional link to Luma event
};

// Helper function to safely get contract address
const getContractAddress = (contractName: string): string => {
  try {
    // @ts-ignore - dynamically accessing contract addresses
    return deployedContracts[8453][contractName]?.address || "";
  } catch (e) {
    return "";
  }
};

// Convert workshop JSON data to locations array
export const locations: Location[] = [
  {
    id: 0,
    position: { lat: 13.7563, lng: 100.5018 },
    title: "Base Batch Workshop - Bangkok, Thailand",
    address: getContractAddress("Bangkok"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 10",
    venue: "TBD",
    lumaLink: "https://lu.ma/1dy944t1",
  },
  {
    id: 1,
    position: { lat: 40.7128, lng: -74.006 },
    title: "Base Batch Workshop - New York City, USA",
    address: getContractAddress("NewYorkCity"),
    image: "/base-batches/na.webp",
    region: "N. America",
    date: "May 4",
    venue: "Variant office",
    lumaLink: "https://lu.ma/vnv007mi",
  },
  {
    id: 2,
    position: { lat: -6.1659, lng: 39.1998 },
    title: "Base Batch Workshop - Zanzibar, Tanzania",
    address: getContractAddress("Zanzibar"),
    image: "/base-batches/africa.webp",
    region: "E Africa",
    date: "May 10",
    venue: "TBD",
    lumaLink: "https://lu.ma/sy1k2af7",
  },
  {
    id: 3,
    position: { lat: 47.3769, lng: 8.5417 },
    title: "Base Batch Workshop - Zug, Switzerland",
    address: getContractAddress("Zug"),
    image: "/base-batches/europe.webp",
    region: "Europe",
    date: "May 13",
    venue: "TBD",
    lumaLink: "https://lu.ma/6jghl0ts",
  },
  {
    id: 4,
    position: { lat: -7.797, lng: 110.3705 },
    title: "Base Batch Workshop - Yogyakarta, Indonesia",
    address: getContractAddress("Yogyakarta"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 3",
    venue: "TBD",
    lumaLink: "https://lu.ma/tiiw11pg",
  },
  {
    id: 5,
    position: { lat: 34.0402, lng: 72.4589 },
    title: "Base Batch Workshop - Swabi, Pakistan",
    address: getContractAddress("Swabi"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "April 24",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 6,
    position: { lat: -23.5505, lng: -46.6333 },
    title: "Base Batch Workshop - São Paulo, Brazil",
    address: getContractAddress("SaoPaulo"),
    image: "/base-batches/latam.webp",
    region: "LATAM",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/4oux3j9x",
  },
  {
    id: 7,
    position: { lat: 37.5665, lng: 126.978 },
    title: "Base Batch Workshop - Seoul, South Korea",
    address: getContractAddress("Seoul"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 8,
    position: { lat: 1.3521, lng: 103.8198 },
    title: "Base Batch Workshop - Singapore",
    address: getContractAddress("Singapore"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 15",
    venue: "TBD",
    lumaLink: "https://lu.ma/tizh5u0t",
  },
  {
    id: 9,
    position: { lat: 41.9028, lng: 12.4964 },
    title: "Base Batch Workshop - Rome, Italy",
    address: getContractAddress("Rome"),
    image: "/base-batches/europe.webp",
    region: "Europe",
    date: "May 6",
    venue: "TBD",
    lumaLink: "https://lu.ma/foxtc7hr",
  },
  {
    id: 10,
    position: { lat: 7.0707, lng: 125.6087 },
    title: "Base Batch Workshop - Panabu City, Philippines",
    address: getContractAddress("PanabuCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 17",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 11,
    position: { lat: 18.5204, lng: 73.8547 },
    title: "Base Batch Workshop - Pune, India",
    address: getContractAddress("Pune"),
    image: "/base-batches/india.webp",
    region: "India",
    date: "April 26",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 12,
    position: { lat: 19.076, lng: 72.8777 },
    title: "Base Batch Workshop - Mumbai, India",
    address: getContractAddress("Mumbai"),
    image: "/base-batches/india.webp",
    region: "India",
    date: "April 27",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 13,
    position: { lat: 13.6228, lng: 123.1948 },
    title: "Base Batch Workshop - Naga City, Philippines",
    address: getContractAddress("NagaCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 6",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 14,
    position: { lat: -1.2921, lng: 36.8219 },
    title: "Base Batch Workshop - Nairobi, Kenya",
    address: getContractAddress("Nairobi"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/x3f1hsuo",
  },
  {
    id: 15,
    position: { lat: 14.5547, lng: 120.998 },
    title: "Base Batch Workshop - Makati City, Philippines",
    address: getContractAddress("MakatiCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 8",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 16,
    position: { lat: 14.8527, lng: 120.816 },
    title: "Base Batch Workshop - Malolos City, Philippines",
    address: getContractAddress("MalolosCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 9",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 17,
    position: { lat: 14.5995, lng: 120.9842 },
    title: "Base Batch Workshop - Manila City, Philippines",
    address: getContractAddress("ManilaCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 9",
    venue: "TBD",
    lumaLink: "https://lu.ma/za6cgxuo",
  },
  {
    id: 18,
    position: { lat: 19.4326, lng: -99.1332 },
    title: "Base Batch Workshop - Mexico City, Mexico",
    address: getContractAddress("MexicoCity"),
    image: "/base-batches/latam.webp",
    region: "LATAM",
    date: "May 11",
    venue: "TBD",
    lumaLink: "https://lu.ma/ysm3jaqt",
  },
  {
    id: 19,
    position: { lat: 6.5244, lng: 3.3792 },
    title: "Base Batch Workshop - Lagos, Nigeria",
    address: getContractAddress("Lagos"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/r7sjp801",
  },
  {
    id: 20,
    position: { lat: 13.1391, lng: 123.5357 },
    title: "Base Batch Workshop - Legazpie City, Philippines",
    address: getContractAddress("LegazpieCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 21,
    position: { lat: 38.7223, lng: -9.1393 },
    title: "Base Batch Workshop - Lisbon, Portugal",
    address: getContractAddress("Lisbon"),
    image: "/base-batches/europe.webp",
    region: "Europe",
    date: "May 10",
    venue: "TBD",
    lumaLink: "https://lu.ma/lisbon-base-workshop",
  },
  {
    id: 22,
    position: { lat: 0.3476, lng: 32.5825 },
    title: "Base Batch Workshop - Kampala, Uganda",
    address: getContractAddress("Kampala"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 4",
    venue: "TBD",
    lumaLink: "https://lu.ma/rrwt99ru",
  },
  {
    id: 23,
    position: { lat: -1.9706, lng: 30.1044 },
    title: "Base Batch Workshop - Kigali, Rwanda",
    address: getContractAddress("Kigali"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 11",
    venue: "TBD",
    lumaLink: "https://lu.ma/rrwt99ru",
  },
  {
    id: 24,
    position: { lat: -0.1022, lng: 34.7617 },
    title: "Base Batch Workshop - Kisumu, Kenya",
    address: getContractAddress("Kisumu"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 4",
    venue: "TBD",
    lumaLink: "https://lu.ma/rrwt99ru",
  },
  {
    id: 25,
    position: { lat: 50.4501, lng: 30.5234 },
    title: "Base Batch Workshop - Kyiv, Ukraine",
    address: getContractAddress("Kyiv"),
    image: "/base-batches/europe.webp",
    region: "Europe",
    date: "May 25",
    venue: "TBD",
    lumaLink: "https://lu.ma/i5tq6zu3",
  },
  {
    id: 26,
    position: { lat: 22.3964, lng: 114.1095 },
    title: "Base Batch Workshop - Hong Kong",
    address: getContractAddress("HongKong"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "April 26",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 27,
    position: { lat: 41.0082, lng: 28.9784 },
    title: "Base Batch Workshop - Istanbul, Turkey",
    address: getContractAddress("Istanbul"),
    image: "/base-batches/europe.webp",
    region: "Europe",
    date: "May 10",
    venue: "TBD",
    lumaLink: "https://lu.ma/l0g71zi9",
  },
  {
    id: 28,
    position: { lat: -6.2088, lng: 106.8456 },
    title: "Base Batch Workshop - Jakarta, Indonesia",
    address: getContractAddress("Jakarta"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 4",
    venue: "TBD",
    lumaLink: "https://lu.ma/5g02dc9i",
  },
  {
    id: 29,
    position: { lat: 28.7041, lng: 77.1025 },
    title: "Base Batch Workshop - Delhi, India",
    address: getContractAddress("Delhi"),
    image: "/base-batches/india.webp",
    region: "India",
    date: "May 3",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 30,
    position: { lat: 6.4531, lng: 7.5176 },
    title: "Base Batch Workshop - Enugu, Nigeria",
    address: getContractAddress("Enugu"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 17",
    venue: "TBD",
    lumaLink: "https://lu.ma/rrwt99ru",
  },
  {
    id: 31,
    position: { lat: 33.9946, lng: 72.9106 },
    title: "Base Batch Workshop - Haripur, Pakistan",
    address: getContractAddress("Haripur"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 7",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 32,
    position: { lat: -6.7924, lng: 39.2083 },
    title: "Base Batch Workshop - Dar Es Salaam, Tanzania",
    address: getContractAddress("DarEsSalaam"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/rrwt99ru",
  },
  {
    id: 33,
    position: { lat: 14.3295, lng: 120.9367 },
    title: "Base Batch Workshop - Dasmariñas, Philippines",
    address: getContractAddress("Dasmarias"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 4",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 34,
    position: { lat: 7.0707, lng: 125.6087 },
    title: "Base Batch Workshop - Davao City, Philippines",
    address: getContractAddress("DavaoCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 25",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 35,
    position: { lat: 10.3185, lng: 123.9175 },
    title: "Base Batch Workshop - Cebu 2, Philippines",
    address: getContractAddress("Cebu2"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 10",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 36,
    position: { lat: 10.3185, lng: 123.9175 },
    title: "Base Batch Workshop - Cebu 3, Philippines",
    address: getContractAddress("Cebu3"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 11",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 37,
    position: { lat: 10.3185, lng: 123.9175 },
    title: "Base Batch Workshop - Cebu, Philippines",
    address: getContractAddress("Cebu"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 8",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 38,
    position: { lat: 16.0544, lng: 108.2022 },
    title: "Base Batch Workshop - Da Nang, Vietnam",
    address: getContractAddress("DaNang"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 12",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 39,
    position: { lat: -34.6037, lng: -58.3816 },
    title: "Base Batch Workshop - Buenos Aires, Argentina",
    address: getContractAddress("BuenosAires"),
    image: "/base-batches/latam.webp",
    region: "LATAM",
    date: "May 21",
    venue: "TBD",
    lumaLink: "https://lu.ma/0hnv2178",
  },
  {
    id: 40,
    position: { lat: 13.6228, lng: 123.3547 },
    title: "Base Batch Workshop - Camarines, Philippines",
    address: getContractAddress("Camarines"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 4",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 41,
    position: { lat: 10.3918, lng: -75.4794 },
    title: "Base Batch Workshop - Cartagena, Colombia",
    address: getContractAddress("Cartagena"),
    image: "/base-batches/latam.webp",
    region: "LATAM",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/9pdvs76k",
  },
  {
    id: 42,
    position: { lat: 12.9716, lng: 77.5946 },
    title: "Base Batch Workshop - Bangalore, India",
    address: getContractAddress("Bangalore"),
    image: "/base-batches/india.webp",
    region: "India",
    date: "April 27",
    venue: "TBD",
    lumaLink: "https://lu.ma/q4a0fz0y",
  },
  {
    id: 43,
    position: { lat: 47.4979, lng: 19.0402 },
    title: "Base Batch Workshop - Budapest, Hungary",
    address: getContractAddress("Budapest"),
    image: "/base-batches/europe.webp",
    region: "Europe",
    date: "May 16",
    venue: "TBD",
    lumaLink: "https://lu.ma/0oaho8e3",
  },
  {
    id: 44,
    position: { lat: 15.1471, lng: 120.5897 },
    title: "Base Batch Workshop - Angeles City, Philippines",
    address: getContractAddress("AngelesCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 23",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 45,
    position: { lat: 29.7601, lng: -95.3701 },
    title: "Base Batch Workshop - Houston, USA",
    address: getContractAddress("Austin"),
    image: "/base-batches/na.webp",
    region: "N. America",
    date: "May 9",
    venue: "TBD",
    lumaLink: "https://lu.ma/agdiik4u",
  },
  {
    id: 46,
    position: { lat: 14.676, lng: 120.5414 },
    title: "Base Batch Workshop - Balanga City, Philippines",
    address: getContractAddress("BalangaCity"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 23",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
  {
    id: 47,
    position: { lat: 9.032, lng: 38.7463 },
    title: "Base Batch Workshop - Addis Ababa, Ethiopia",
    address: getContractAddress("AddisAbaba"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 18",
    venue: "TBD",
    lumaLink: "https://lu.ma/rrwt99ru",
  },
  {
    id: 48,
    position: { lat: 5.6037, lng: -0.187 },
    title: "Base Batch Workshop - Accra, Ghana",
    address: getContractAddress("Accra"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 10",
    venue: "TBD",
    lumaLink: "https://lu.ma/prj5e77i",
  },
  {
    id: 49,
    position: { lat: 9.0765, lng: 7.3986 },
    title: "Base Batch Workshop - Abuja, Nigeria",
    address: getContractAddress("Abuja"),
    image: "/base-batches/africa.webp",
    region: "Africa",
    date: "May 11",
    venue: "TBD",
    lumaLink: "https://lu.ma/rrwt99ru",
  },
  {
    id: 50,
    position: { lat: 7.2906, lng: 80.6337 },
    title: "Base Batch Workshop - Tagum, Philippines",
    address: getContractAddress("Tagum"),
    image: "/base-batches/apac.webp",
    region: "APAC",
    date: "May 3",
    venue: "TBD",
    lumaLink: "https://lu.ma/zujqeul1",
  },
];
